
spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/startshineye/config-repo
          basedir: D:/config-repo/basedir
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8083